// Post-Mortem Generator
//
// LLM-first: the report content is entirely generated by the LLM from the
// raw incident data. This is NOT template filling - the LLM reasons over all
// available signals to produce an original narrative for each section.

import { randomUUID } from 'node:crypto';
import type { LLMGateway } from '@agentic-obs/llm-gateway';
import { LLMUnavailableError } from '@agentic-obs/common';
import type {
  PostMortemReport,
  PostMortemInput,
  PostMortemTimelineEntry,
} from './post-mortem-types.js';

// - Internal LLM response shape --------------------------------------------

interface LLMPostMortemResponse {
  summary?: unknown;
  impact?: unknown;
  timeline?: unknown;
  rootCause?: unknown;
  actionsTaken?: unknown;
  lessonsLearned?: unknown;
  actionItems?: unknown;
}

// - Generator --------------------------------------------------------------

export class PostMortemGenerator {
  private readonly llm: LLMGateway;

  constructor(config: { llm: LLMGateway }) {
    this.llm = config.llm;
  }

  /**
   * Generate a post-mortem report by prompting the LLM with all available
   * incident, investigation, execution, and verification data.
   *
   * Throws LLMUnavailableError if the LLM call fails or returns unparseable output.
   * Callers should surface AI unavailable - please retry to the user.
   */
  async generate(input: PostMortemInput): Promise<PostMortemReport> {
    const id = randomUUID().slice(0, 8);
    const generatedAt = new Date().toISOString();

    let raw: string;
    try {
      const response = await this.llm.complete(
        [
          {
            role: 'system',
            content:
              'You are an expert SRE technical writer. Analyse the provided incident data and write a comprehensive post-mortem report. Your output must be a single valid JSON object matching the required schema. Every field must contain original, specific, insightful content derived from the data - never use placeholder text.',
          },
          {
            role: 'user',
            content: this.buildPrompt(input),
          },
        ],
        {
          model: 'claude-sonnet-4-5',
          temperature: 0.2,
          maxTokens: 3000,
          responseFormat: 'json',
        },
      );
      raw = response.content;
    } catch (err) {
      throw new LLMUnavailableError(
        err instanceof Error ? err.message : 'LLM post-mortem generation failed',
      );
    }

    return this.parseResponse(raw, id, input, generatedAt);
  }

  // - Private helpers ------------------------------------------------------

  private buildPrompt(input: PostMortemInput): string {
    return JSON.stringify(
      {
        instruction: [
          'Write a post-mortem report for the following incident.',
          'Synthesize all data to produce specific, actionable, non-generic content.',
          'Do not repeat the raw data verbatim; reason about it.',
        ].join(' '),
        incident: input.incident,
        investigations: input.investigations,
        executionResults: input.executionResults ?? [],
        verificationOutcomes: input.verificationOutcomes ?? [],
        responseSchema: {
          summary: 'string - 2-4 sentence executive overview of what happened and its impact',
          impact:
            'string - affected services, estimated users/revenue impact, duration of degradation',
          timeline: [
            {
              timestamp: 'ISO-8601',
              description: 'string - what happened at this moment',
            },
          ],
          rootCause: 'string - precise technical root cause with supporting evidence',
          actionsTaken: ['string - each remediation step taken during the incident'],
          lessonsLearned: ['string - specific insight derived from this incident'],
          actionItems: [
            'string - concrete follow-up task in imperative form, e.g. "Add circuit breaker to checkout-service -> payment-service calls"',
          ],
        },
      },
      null,
      2,
    );
  }

  private parseResponse(
    raw: string,
    id: string,
    input: PostMortemInput,
    generatedAt: string,
  ): PostMortemReport {
    let parsed: unknown;
    try {
      const trimmed = raw.trim();
      const fenceMatch = trimmed.match(/^```(?:json)?\s*\n?([\s\S]*?)\n?```$/i);
      parsed = JSON.parse(fenceMatch?.[1]?.trim() ?? trimmed);
    } catch {
      throw new LLMUnavailableError('LLM returned unparseable post-mortem response');
    }

    if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
      throw new LLMUnavailableError('LLM returned invalid post-mortem response structure');
    }

    const obj = parsed as LLMPostMortemResponse;

    const timeline: PostMortemTimelineEntry[] = Array.isArray(obj.timeline)
      ? obj.timeline
          .filter(
            (
              e,
            ): e is {
              timestamp: string;
              description: string;
            } =>
              typeof e === 'object' &&
              e !== null &&
              typeof (e as Record<string, unknown>).timestamp === 'string' &&
              typeof (e as Record<string, unknown>).description === 'string',
          )
          .map((e) => ({ timestamp: e.timestamp, description: e.description }))
      : [];

    return {
      id,
      incidentId: input.incident.id,
      summary:
        typeof obj.summary === 'string'
          ? obj.summary
          : `Incident ${input.incident.id} post-mortem`,
      impact:
        typeof obj.impact === 'string'
          ? obj.impact
          : `Services: ${input.incident.services.join(', ')}`,
      timeline,
      rootCause:
        typeof obj.rootCause === 'string' ? obj.rootCause : 'Root cause analysis pending.',
      actionsTaken: Array.isArray(obj.actionsTaken) ? obj.actionsTaken.map(String) : [],
      lessonsLearned: Array.isArray(obj.lessonsLearned) ? obj.lessonsLearned.map(String) : [],
      actionItems: Array.isArray(obj.actionItems) ? obj.actionItems.map(String) : [],
      generatedAt,
      generatedBy: 'llm',
    };
  }
}
