import { pgAll, pgRun } from './pg-helpers.js';
/**
 * DashboardRepository — Postgres-backed dashboard store (W6 / T6.A1).
 *
 * Replaces the in-memory `defaultDashboardStore` from
 * packages/data-layer/src/stores/dashboard-store.ts. Row shape matches
 * the `dashboards` table declared in db/sqlite-schema.ts (migration
 * already applied — no new DDL).
 *
 * Style mirrors the W2 instance-config repositories: raw `sql` template
 * literals via the drizzle client's `all` / `run`, JSON.stringify on
 * write for array/object columns, JSON.parse with an empty-array fallback
 * on read, ISO-8601 timestamps generated by the repo (not SQL) so all
 * writes share a single `now` value.
 *
 * Semantics (differ from the legacy store):
 *   - findById / update / updateStatus / updatePanels / updateVariables
 *     return `null` (not `undefined`) when the id is unknown.
 *   - No capacity eviction — Postgres is the durable store and we rely on
 *     operator-scoped retention rather than a 500-row LRU.
 *   - No markDirty() — every write is already durable the moment `run`
 *     returns.
 *   - No version-store side effects — version snapshots belong to the
 *     version repository and should be wired at the route layer, not
 *     buried in a CRUD primitive.
 *
 * A back-compat `PostgresDashboardRepository` class is re-exported below
 * for the existing data-layer factory wiring — it delegates to the same
 * W2 repo but adapts return types to the legacy `undefined` convention
 * used by `packages/data-layer/src/repository/interfaces.ts`. The
 * A.merge parent will collapse the two once route handlers are migrated
 * to the W2 interface.
 */

import { randomUUID } from 'node:crypto';
import { sql } from 'drizzle-orm';
import type {
  Dashboard,
  DashboardStatus,
  DashboardVariable,
  DashboardType,
  PanelConfig,
  PublishStatus,
  IDashboardRepository,
  NewDashboardInput,
  DashboardPatch,
} from '@agentic-obs/common';
import type { IDashboardRepository as ILegacyDashboardRepository } from '../interfaces.js';

// -- Row shape ---------------------------------------------------------

interface DashboardRow {
  id: string;
  type: string;
  title: string;
  description: string;
  prompt: string;
  user_id: string;
  status: string;
  panels: string;
  variables: string;
  refresh_interval_sec: number;
  datasource_ids: string;
  use_existing_metrics: number;
  folder: string | null;
  workspace_id: string | null;
  org_id: string;
  version: number | null;
  publish_status: string | null;
  error: string | null;
  created_at: string;
  updated_at: string;
}

function nowIso(): string {
  return new Date().toISOString();
}

function parseJsonArray<T>(raw: string | null | undefined, fallback: T[] = []): T[] {
  if (raw === null || raw === undefined || raw === '') return fallback;
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? (parsed as T[]) : fallback;
  } catch {
    return fallback;
  }
}

function toBool(v: unknown): boolean {
  if (typeof v === 'boolean') return v;
  return Number(v) === 1;
}

function fromBool(v: boolean | undefined, dflt = false): number {
  return (v ?? dflt) ? 1 : 0;
}

function rowToDashboard(r: DashboardRow): Dashboard {
  const base: Dashboard = {
    id: r.id,
    type: (r.type || 'dashboard') as DashboardType,
    title: r.title,
    description: r.description,
    prompt: r.prompt,
    userId: r.user_id,
    status: r.status as DashboardStatus,
    panels: parseJsonArray<PanelConfig>(r.panels, []),
    variables: parseJsonArray<DashboardVariable>(r.variables, []),
    refreshIntervalSec: r.refresh_interval_sec,
    datasourceIds: parseJsonArray<string>(r.datasource_ids, []),
    useExistingMetrics: toBool(r.use_existing_metrics),
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  };
  if (r.folder !== null) base.folder = r.folder;
  if (r.workspace_id !== null) base.workspaceId = r.workspace_id;
  if (r.version !== null) base.version = r.version;
  if (r.publish_status !== null) base.publishStatus = r.publish_status as PublishStatus;
  if (r.error !== null) base.error = r.error;
  return base;
}

/**
 * W2-style SQLite impl of the shared IDashboardRepository.
 */
export class DashboardRepository implements IDashboardRepository {
  constructor(private readonly db: any) {}

  async create(input: NewDashboardInput): Promise<Dashboard> {
    const id = randomUUID();
    const now = nowIso();
    const panelsJson = JSON.stringify([]);
    const variablesJson = JSON.stringify([]);
    const datasourceIdsJson = JSON.stringify(input.datasourceIds ?? []);
    const useExistingMetrics = fromBool(input.useExistingMetrics, true);

    await pgRun(this.db, sql`
      INSERT INTO dashboards (
        id, type, title, description, prompt, user_id, status,
        panels, variables, refresh_interval_sec, datasource_ids,
        use_existing_metrics, folder, workspace_id,
        created_at, updated_at
      ) VALUES (
        ${id},
        ${'dashboard'},
        ${input.title},
        ${input.description},
        ${input.prompt},
        ${input.userId},
        ${'generating'},
        ${panelsJson},
        ${variablesJson},
        ${30},
        ${datasourceIdsJson},
        ${useExistingMetrics},
        ${input.folder ?? null},
        ${input.workspaceId ?? null},
        ${now},
        ${now}
      )
    `);
    const saved = await this.findById(id);
    if (!saved) {
      throw new Error(`[DashboardRepository] create: row ${id} not found after insert`);
    }
    return saved;
  }

  async findById(id: string): Promise<Dashboard | null> {
    const rows = await pgAll<DashboardRow>(this.db,
      sql`SELECT * FROM dashboards WHERE id = ${id} LIMIT 1`,
    );
    if (rows.length === 0) return null;
    return rowToDashboard(rows[0]!);
  }

  /**
   * Folder-uid lookup used by the RBAC dashboards resolver to cascade a
   * grant on a folder's scope to any dashboard it contains. Org-scoped so
   * one org can't reach into another's row.
   */
  async getFolderUid(orgId: string, dashboardId: string): Promise<string | null> {
    const rows = await pgAll<{ folder_uid: string | null }>(this.db,
      sql`SELECT folder_uid FROM dashboards WHERE org_id = ${orgId} AND id = ${dashboardId} LIMIT 1`,
    );
    return rows[0]?.folder_uid ?? null;
  }

  async findAll(userId?: string): Promise<Dashboard[]> {
    const rows =
      userId === undefined
        ? await pgAll<DashboardRow>(this.db, sql`SELECT * FROM dashboards ORDER BY created_at DESC`)
        : await pgAll<DashboardRow>(this.db,
            sql`SELECT * FROM dashboards WHERE user_id = ${userId} ORDER BY created_at DESC`,
          );
    return rows.map(rowToDashboard);
  }

  async listByWorkspace(workspaceId: string): Promise<Dashboard[]> {
    const rows = await pgAll<DashboardRow>(this.db,
      sql`SELECT * FROM dashboards WHERE workspace_id = ${workspaceId} ORDER BY created_at DESC`,
    );
    return rows.map(rowToDashboard);
  }

  async update(id: string, patch: DashboardPatch): Promise<Dashboard | null> {
    const existing = await this.findById(id);
    if (!existing) return null;
    const now = nowIso();
    const merged = {
      type: patch.type ?? existing.type,
      title: patch.title ?? existing.title,
      description: patch.description ?? existing.description,
      panels: patch.panels ?? existing.panels,
      variables: patch.variables ?? existing.variables,
      refreshIntervalSec: patch.refreshIntervalSec ?? existing.refreshIntervalSec,
      folder: patch.folder !== undefined ? patch.folder : (existing.folder ?? null),
    };
    await pgRun(this.db, sql`
      UPDATE dashboards SET
        type                 = ${merged.type},
        title                = ${merged.title},
        description          = ${merged.description},
        panels               = ${JSON.stringify(merged.panels)},
        variables            = ${JSON.stringify(merged.variables)},
        refresh_interval_sec = ${merged.refreshIntervalSec},
        folder               = ${merged.folder ?? null},
        updated_at           = ${now}
      WHERE id = ${id}
    `);
    return this.findById(id);
  }

  async updateStatus(
    id: string,
    status: DashboardStatus,
    error?: string,
  ): Promise<Dashboard | null> {
    const existing = await this.findById(id);
    if (!existing) return null;
    const now = nowIso();
    // `error === undefined` means "don't touch the error column"; pass
    // null to explicitly clear it. The legacy store only ever set error;
    // it never cleared it. Preserve that by leaving the column alone
    // when `error` arg is undefined.
    if (error === undefined) {
      await pgRun(this.db, sql`
        UPDATE dashboards SET status = ${status}, updated_at = ${now}
        WHERE id = ${id}
      `);
    } else {
      await pgRun(this.db, sql`
        UPDATE dashboards SET
          status     = ${status},
          error      = ${error},
          updated_at = ${now}
        WHERE id = ${id}
      `);
    }
    return this.findById(id);
  }

  async updatePanels(id: string, panels: PanelConfig[]): Promise<Dashboard | null> {
    const existing = await this.findById(id);
    if (!existing) return null;
    const now = nowIso();
    await pgRun(this.db, sql`
      UPDATE dashboards SET
        panels     = ${JSON.stringify(panels)},
        updated_at = ${now}
      WHERE id = ${id}
    `);
    return this.findById(id);
  }

  async updateVariables(
    id: string,
    variables: DashboardVariable[],
  ): Promise<Dashboard | null> {
    const existing = await this.findById(id);
    if (!existing) return null;
    const now = nowIso();
    await pgRun(this.db, sql`
      UPDATE dashboards SET
        variables  = ${JSON.stringify(variables)},
        updated_at = ${now}
      WHERE id = ${id}
    `);
    return this.findById(id);
  }

  async delete(id: string): Promise<boolean> {
    const existing = await this.findById(id);
    if (!existing) return false;
    await pgRun(this.db, sql`DELETE FROM dashboards WHERE id = ${id}`);
    return true;
  }

  async size(): Promise<number> {
    const rows = await pgAll<{ n: number }>(this.db, sql`SELECT COUNT(*) AS n FROM dashboards`);
    return rows[0]?.n ?? 0;
  }

  async clear(): Promise<void> {
    await pgRun(this.db, sql`DELETE FROM dashboards`);
  }

  async toJSON(): Promise<Dashboard[]> {
    return this.findAll();
  }

  async loadJSON(data: unknown): Promise<void> {
    if (!Array.isArray(data)) return;
    for (const raw of data as Dashboard[]) {
      if (!raw || typeof raw.id !== 'string' || raw.id === '') continue;
      // Upsert: preserves existing rows when the import set and the DB
      // overlap, mirrors the old loadJSON's "last-write-wins via Map.set".
      await pgRun(this.db, sql`
        INSERT INTO dashboards (
          id, type, title, description, prompt, user_id, status,
          panels, variables, refresh_interval_sec, datasource_ids,
          use_existing_metrics, folder, workspace_id,
          version, publish_status, error, created_at, updated_at
        ) VALUES (
          ${raw.id},
          ${raw.type ?? 'dashboard'},
          ${raw.title ?? ''},
          ${raw.description ?? ''},
          ${raw.prompt ?? ''},
          ${raw.userId ?? ''},
          ${raw.status ?? 'generating'},
          ${JSON.stringify(raw.panels ?? [])},
          ${JSON.stringify(raw.variables ?? [])},
          ${raw.refreshIntervalSec ?? 30},
          ${JSON.stringify(raw.datasourceIds ?? [])},
          ${fromBool(raw.useExistingMetrics, true)},
          ${raw.folder ?? null},
          ${raw.workspaceId ?? null},
          ${raw.version ?? null},
          ${raw.publishStatus ?? null},
          ${raw.error ?? null},
          ${raw.createdAt ?? nowIso()},
          ${raw.updatedAt ?? nowIso()}
        )
        ON CONFLICT(id) DO UPDATE SET
          type                 = excluded.type,
          title                = excluded.title,
          description          = excluded.description,
          prompt               = excluded.prompt,
          user_id              = excluded.user_id,
          status               = excluded.status,
          panels               = excluded.panels,
          variables            = excluded.variables,
          refresh_interval_sec = excluded.refresh_interval_sec,
          datasource_ids       = excluded.datasource_ids,
          use_existing_metrics = excluded.use_existing_metrics,
          folder               = excluded.folder,
          workspace_id         = excluded.workspace_id,
          version              = excluded.version,
          publish_status       = excluded.publish_status,
          error                = excluded.error,
          created_at           = excluded.created_at,
          updated_at           = excluded.updated_at
      `);
    }
  }
}

/**
 * Legacy class retained for the existing data-layer factory (which still
 * wires `PostgresDashboardRepository` into the pre-W6 `IDashboardRepository`
 * from packages/data-layer/src/repository/interfaces.ts). The legacy
 * interface returns `undefined` for missing rows; the W2 impl returns
 * `null`. Adapt by mapping null → undefined at the edge, so route
 * handlers that still branch on `=== undefined` keep working until the
 * A.merge parent migrates them.
 */
export class PostgresDashboardRepository implements ILegacyDashboardRepository {
  private readonly inner: DashboardRepository;

  constructor(db: any) {
    this.inner = new DashboardRepository(db);
  }

  async create(params: NewDashboardInput): Promise<Dashboard> {
    return this.inner.create(params);
  }

  async findById(id: string): Promise<Dashboard | undefined> {
    return (await this.inner.findById(id)) ?? undefined;
  }

  async findAll(userId?: string): Promise<Dashboard[]> {
    return this.inner.findAll(userId);
  }

  async listByWorkspace(workspaceId: string): Promise<Dashboard[]> {
    return this.inner.listByWorkspace(workspaceId);
  }

  async update(id: string, patch: DashboardPatch): Promise<Dashboard | undefined> {
    return (await this.inner.update(id, patch)) ?? undefined;
  }

  async updateStatus(
    id: string,
    status: DashboardStatus,
    error?: string,
  ): Promise<Dashboard | undefined> {
    return (await this.inner.updateStatus(id, status, error)) ?? undefined;
  }

  async updatePanels(id: string, panels: PanelConfig[]): Promise<Dashboard | undefined> {
    return (await this.inner.updatePanels(id, panels)) ?? undefined;
  }

  async updateVariables(
    id: string,
    variables: DashboardVariable[],
  ): Promise<Dashboard | undefined> {
    return (await this.inner.updateVariables(id, variables)) ?? undefined;
  }

  async delete(id: string): Promise<boolean> {
    return this.inner.delete(id);
  }

  /** Pass-through to the W2 impl so RBAC resolver wiring can call it
   * without reaching for the underlying SQLite client. */
  async getFolderUid(orgId: string, dashboardId: string): Promise<string | null> {
    return this.inner.getFolderUid(orgId, dashboardId);
  }
}
